apiVersion: apps/v1
kind: Deployment
metadata:
  name: cute-dogs-backend
spec:
  selector:
    matchLabels:
      app: cute-dogs-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: cute-dogs-backend
    spec:
      containers:
      - name: cute-dogs-backend
        image: luizportel4/cute-dogs-backend:2.2.3
        resources:
          limits:
            memory: "50Mi"
            cpu: "100m"
        ports:
        - name: http
          containerPort: 3001
        env:
          - name: MONGO_DB
            value: "your mongodb name"
          - name: MONGO_COLLECTION
            value: "your-collection" 
        envFrom:
          - secretRef:
              name: secret-backend