apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cute-dogs-hpa-backend
spec:
  scaleTargetRef: 
    apiVersion: apps/v1
    name: cute-dogs-backend
    kind: Deployment
  minReplicas: 1
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70