apiVersion: v1
kind: Service
metadata:
  name: service-backend
spec:
  type: ClusterIP
  selector:
    app: cute-dogs-backend
  ports:
  - name: service-backend 
    port: 3001
    targetPort: 3001
    protocol: TCP
